# Generated by Django 4.2.5 on 2023-09-18 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('sno', models.IntegerField(db_column='SNO', primary_key=True, serialize=False)),
                ('event_name', models.CharField(blank=True, max_length=50, null=True)),
                ('data', models.TextField(blank=True, null=True)),
                ('time', models.DateTimeField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=40, null=True)),
                ('image', models.CharField(blank=True, max_length=2000, null=True)),
                ('is_liked', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'events',
                'managed': True,
            },
        ),
    ]
